"""add status

Revision ID: 15320ac89740
Revises: 7d8e59361ddc
Create Date: 2026-03-24 22:07:54.542956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15320ac89740'
down_revision: Union[str, Sequence[str], None] = '7d8e59361ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'status')
    # ### end Alembic commands ###
