"""Add UserOnboarding model and Tenant trial ends at

Revision ID: 53442e28731f
Revises: 6a38e5c4ebaa
Create Date: 2026-05-23 20:53:03.159025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53442e28731f'
down_revision: Union[str, Sequence[str], None] = '6a38e5c4ebaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboardings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('website_name', sa.String(), nullable=True),
    sa.Column('website_type', sa.String(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_monitor_ids', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_onboardings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_onboardings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_onboardings')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_user_onboardings_tenant_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_onboardings_user_id'))
    )
    with op.batch_alter_table('user_onboardings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_onboardings_id'), ['id'], unique=False)

    op.create_table('monitor_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('uptime_monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('ssl_monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('performance_checks_enabled', sa.Boolean(), nullable=True),
    sa.Column('incident_logging_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('defaults', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['user_onboardings.id'], name=op.f('fk_monitor_preferences_onboarding_id_user_onboardings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_monitor_preferences_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_monitor_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_preferences')),
    sa.UniqueConstraint('onboarding_id', name=op.f('uq_monitor_preferences_onboarding_id'))
    )
    with op.batch_alter_table('monitor_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_preferences_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_dashboard', sa.Boolean(), nullable=True),
    sa.Column('alert_email', sa.String(), nullable=True),
    sa.Column('weekly_reports', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['user_onboardings.id'], name=op.f('fk_notification_settings_onboarding_id_user_onboardings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    sa.UniqueConstraint('onboarding_id', name=op.f('uq_notification_settings_onboarding_id'))
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_settings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_settings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('monitor_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ping_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('html_hash', sa.String(), nullable=True))

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_html_hash', sa.String(), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('trial_ends_at')

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('last_html_hash')

    with op.batch_alter_table('monitor_logs', schema=None) as batch_op:
        batch_op.drop_column('html_hash')
        batch_op.drop_column('ping_ms')

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_settings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_settings_id'))

    op.drop_table('notification_settings')

    with op.batch_alter_table('monitor_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_preferences_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_preferences_id'))

    op.drop_table('monitor_preferences')

    with op.batch_alter_table('user_onboardings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_onboardings_id'))

    op.drop_table('user_onboardings')
    # ### end Alembic commands ###
