"""Add tenant and billing models

Revision ID: 6a38e5c4ebaa
Revises: 6dec92308518
Create Date: 2026-05-03 11:48:32.696889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a38e5c4ebaa'
down_revision: Union[str, Sequence[str], None] = '6dec92308518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_monitors_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_monitors_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
