"""Add extended metrics to MonitorLog

Revision ID: 6dec92308518
Revises: 4829bf73cb23
Create Date: 2026-05-03 11:09:38.412837

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = '6dec92308518'
down_revision: Union[str, Sequence[str], None] = '4829bf73cb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('monitor_logs', sa.Column('ssl_issuer', sa.String(), nullable=True))
    op.add_column('monitor_logs', sa.Column('ssl_days_remaining', sa.Integer(), nullable=True))
    op.add_column('monitor_logs', sa.Column('tls_handshake_ms', sa.Integer(), nullable=True))
    op.add_column('monitor_logs', sa.Column('ttfb_ms', sa.Integer(), nullable=True))
    op.add_column('monitor_logs', sa.Column('redirects', sa.Integer(), nullable=True))
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_logs', 'redirects')
    op.drop_column('monitor_logs', 'ttfb_ms')
    op.drop_column('monitor_logs', 'tls_handshake_ms')
    op.drop_column('monitor_logs', 'ssl_days_remaining')
    op.drop_column('monitor_logs', 'ssl_issuer')
    # ### end Alembic commands ###
