import time

def mock_ai_stream(prompt: str):
    demo_response = (
        "Here is a secure analysis generated by HOME's private AI assistant.\n\n"
        "• SSL expiry detected risk: HIGH\n"
        "• Recommended action: Renew certificate immediately\n"
        "• Compliance impact: PCI-DSS, GDPR\n\n"
        "No sensitive data was sent to any public AI service."
    )

    for word in demo_response.split():
        yield word + " "
        time.sleep(0.05)
