from enum import Enum

class FailureType(str, Enum):
    UP = "UP"
    DNS_FAILURE = "DNS_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    TIMEOUT = "TIMEOUT"
    SERVER_ERROR = "SERVER_ERROR"
    CLIENT_ERROR = "CLIENT_ERROR"
    PERFORMANCE_DEGRADED = "PERFORMANCE_DEGRADED"
    UNKNOWN = "UNKNOWN"
